name: Deployment Pipeline

on:
  push:
    branches:
      - development
      - master

jobs:
  build:
    name: Build and push the Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY_USERNAME }}/my-event:${{ github.sha }}
        env:
          NODE_ENV: ${{ env.NODE_ENV }}
          API_URL: ${{ env.API_URL }}

  deploy:
    name: Deploy the Docker image to the server
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker pull ${{ secrets.DOCKER_REGISTRY_USERNAME }}/my-event:${{ github.sha }}
            docker stop ${{ env.DOCKER_APP_NAME }} || true
            docker rm ${{ env.DOCKER_APP_NAME }} || true
            docker run -d --name ${{ env.DOCKER_APP_NAME }} -p 5000:5000 ${{ secrets.DOCKER_REGISTRY_USERNAME }}/my-event:${{ github.sha }}
