name: Pull Request Checks

on:
  pull_request:
    branches:
      - development
  push:
    branches:
      - development

jobs:
  lint:
    name: Lint the source code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install

      - name: Run the linter
        run: yarn lint
